on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          failOnError: true
          commitMode: true
          configuration: ".release-notes-config.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          npm install
          npm run build

      - name: Create Release (Sonos)
        uses: softprops/action-gh-release@v2
        with:
          body: ${{steps.build_changelog.outputs.changelog}}
          prerelease: true
          files: "${{ github.workspace }}/dist/custom-sonos-card.js"

      - name: Create Release (Mxmp)
        uses: softprops/action-gh-release@v2
        with:
          body: ${{steps.build_changelog.outputs.changelog}}
          repository: punxaphil/maxi-media-player
          prerelease: true
          token: ${{ secrets.PAT_TOKEN }}
          files: "${{ github.workspace }}/dist-maxi-media-player/maxi-media-player.js"

